version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "typescript-eslint"
      tanstack-start-router:
        patterns:
          - "@tanstack/react-router"
          - "@tanstack/react-router-*"
          - "@tanstack/react-start"
          - "@tanstack/react-start-*"
          - "@tanstack/router-*"
          - "@tanstack/start-*"
      vite:
        patterns:
          - "@vitejs/*"
          - "@vitest/*"
          - "vite"
          - "vite-*"
          - "vitest"
