version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      tanstack-start-router:
        patterns:
          - "@tanstack/react-router"
          - "@tanstack/react-router-*"
          - "@tanstack/react-start"
          - "@tanstack/react-start-*"
          - "@tanstack/router-*"
          - "@tanstack/start-*"
