# Funding support for ElevenLabs.io

github: [ryleetikelgreene, josephlung]
patreon: elevenlabs
open_collective: elevenlabs
ko_fi: elevenlabs
tidelift: # Not currently available
community_bridge: # Not currently available
liberapay: elevenlabs
issuehunt: # Not currently available
lfx_crowdfunding: # Not currently available
polar: # Not currently available
buy_me_a_coffee: elevenlabs
thanks_dev: # Not currently available
custom: ["https://elevenlabs.io/funding", "https://elevenlabs.io/donate"]